################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ASW \
ASW/Time \
BSW/CommonInclude \
BSW/Communication/CAN/CanIf \
BSW/Communication/CAN/CanNm \
BSW/Communication/CAN/CanSM \
BSW/Communication/CAN/CanTp \
BSW/Communication/Common/Com \
BSW/Communication/Common/Dcm \
BSW/Communication/Common/Dcm/DcmDsd \
BSW/Communication/Common/Dcm/DcmDsl \
BSW/Communication/Common/Dcm/DcmDsp \
BSW/Communication/Common/Dcm/DcmDsp/OBD \
BSW/Communication/Common/Dcm/DcmDsp/UDS \
BSW/Communication/Common/NmIf \
BSW/Communication/Common/PDUR \
BSW/Communication/XCP \
BSW/Memmory/Crc \
BSW/Memmory/MemIf \
BSW/Memmory/NvM \
BSW/SystemService/BswM \
BSW/SystemService/ComM \
BSW/SystemService/Dem \
BSW/SystemService/E2E \
BSW/SystemService/EcuM \
BSW/SystemService/FreeRTimer \
BSW/SystemService/Os/Arch \
BSW/SystemService/Os/Kernel \
CDD/CddHsm/Cry \
CDD/CddHsm/Demo \
CDD/CddHsm/Hsm_Com \
CDD/CddHsm/Hsm_Mcal \
CDD/CddHsm/TestCode/UserTest_Task \
CDD/CddHsm/TestCode/demoapp/src \
CDD/Power \
CDD/SysVol \
CDD/TLF35584 \
CDD/UDS \
CDD/Wdg_17_Scu \
Config/BSW_Config \
Config/MCAL_Config/src \
Config/Memory_Config \
Config/Os_Config \
Config/RTE_Config \
. \
Flash_Drv/DFlash \
Flash_Drv/PFlash \
Libraries/Bsp \
Libraries/Compilers \
Libraries/Flash/Std \
Libraries/Impl \
MCAL/Adc/ssc/src \
MCAL/Autosar_Srv \
MCAL/Bfx/ssc/src \
MCAL/Can_17_McmCan/ssc/src \
MCAL/Dio/ssc/src \
MCAL/Dma/ssc/src \
MCAL/Fee/ssc/src \
MCAL/FlsLoader/Ssc/src \
MCAL/Fls_17_Dmu/ssc/src \
MCAL/Icu_17_TimerIp/ssc/src \
MCAL/Integration \
MCAL/Irq/ssc/src \
MCAL/McalLib/ssc/src \
MCAL/Mcu/ssc/src \
MCAL/Port/ssc/src \
MCAL/Pwm_17_GtmCcu6/ssc/src \
MCAL/Spi/ssc/src \
MCAL/Ssw/TC37A/Common \
MCAL/Ssw/TC37A/Irq/Traps \
MCAL/Ssw/TC37A/Tricore \
MCAL/Tricore/Cfg_Ssw/TC37A \
MCAL/Wdg_17_Scu/ssc/src \
Swap/UCB_Driver \
Swap \

