/*============================================================================*/
/*  Copyright (C) iSOFT   (2020), iSOFT INFRASTRUCTURE SOFTWARE CO.,LTD.
 *  
 *  All rights reserved. This software is iSOFT property. Duplication 
 *  or disclosure without iSOFT written authorization is prohibited.
 *  
 *  @file       <UDS_MemMap.h>
 *  @brief      <>
 *  
 *  <MCU:TC377>
 *  
 *  @author     <>
 *  @date       <2023-03-29 10:48:53>
 */
/*============================================================================*/

/* UDS_MemMap.h */

#ifndef UDS_MEMMAP_H
#define UDS_MEMMAP_H

/*******************************************************************************
 **                        Revision Control History                           **
******************************************************************************/

/*******************************************************************************
 **                        Version Information                                **
******************************************************************************/

/*******************************************************************************
 **                        Include Section                                    **
******************************************************************************/

/* Mapping of Code */
#ifdef UDS_START_SEC_CODE
    #undef UDS_START_SEC_CODE
    #define START_SEC_CODE
#elif defined UDS_STOP_SEC_CODE
    #undef UDS_STOP_SEC_CODE
    #define STOP_SEC_CODE
#elif defined UDS_START_SEC_CALLOUT_CODE
    #undef UDS_START_SEC_CALLOUT_CODE
    #define START_SEC_CALLOUT_CODE
#elif defined UDS_STOP_SEC_CALLOUT_CODE
    #undef UDS_STOP_SEC_CALLOUT_CODE
    #define STOP_SEC_CALLOUT_CODE
#elif defined UDS_START_SEC_CALLBACK_CODE
    #undef UDS_START_SEC_CALLBACK_CODE
    #define START_SEC_CALLBACK_CODE
#elif defined UDS_STOP_SEC_CALLBACK_CODE
    #undef UDS_STOP_SEC_CALLBACK_CODE
    #define STOP_SEC_CALLBACK_CODE
#elif defined UDS_START_SEC_CODE_FAST
    #undef UDS_START_SEC_CODE_FAST
    #define START_SEC_CODE_FAST
#elif defined UDS_STOP_SEC_CODE_FAST
    #undef UDS_STOP_SEC_CODE_FAST
    #define STOP_SEC_CODE_FAST

/* Mapping of Variables */
/* VAR_NO_INIT */
#elif defined UDS_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_NO_INIT_BOOLEAN
    #define START_SEC_VAR_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #define STOP_SEC_VAR_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_NO_INIT_8
    #undef UDS_START_SEC_VAR_NO_INIT_8
    #define START_SEC_VAR_NO_INIT_8
#elif defined UDS_STOP_SEC_VAR_NO_INIT_8
    #undef UDS_STOP_SEC_VAR_NO_INIT_8
    #define STOP_SEC_VAR_NO_INIT_8
#elif defined UDS_START_SEC_VAR_NO_INIT_16
    #undef UDS_START_SEC_VAR_NO_INIT_16
    #define START_SEC_VAR_NO_INIT_16
#elif defined UDS_STOP_SEC_VAR_NO_INIT_16
    #undef UDS_STOP_SEC_VAR_NO_INIT_16
    #define STOP_SEC_VAR_NO_INIT_16
#elif defined UDS_START_SEC_VAR_NO_INIT_32
    #undef UDS_START_SEC_VAR_NO_INIT_32
    #define START_SEC_VAR_NO_INIT_32
#elif defined UDS_STOP_SEC_VAR_NO_INIT_32
    #undef UDS_STOP_SEC_VAR_NO_INIT_32
    #define STOP_SEC_VAR_NO_INIT_32
#elif defined UDS_START_SEC_VAR_NO_INIT_PTR
    #undef UDS_START_SEC_VAR_NO_INIT_PTR
    #define START_SEC_VAR_NO_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_NO_INIT_PTR
    #undef UDS_STOP_SEC_VAR_NO_INIT_PTR
    #define STOP_SEC_VAR_NO_INIT_PTR
#elif defined UDS_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #define START_SEC_VAR_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_NO_INIT_UNSPECIFIED

/* VAR_CLEARED */
#elif defined UDS_START_SEC_VAR_CLEARED_BOOLEAN
    #undef UDS_START_SEC_VAR_CLEARED_BOOLEAN
    #define START_SEC_VAR_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_VAR_CLEARED_BOOLEAN
    #define STOP_SEC_VAR_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_VAR_CLEARED_8
    #undef UDS_START_SEC_VAR_CLEARED_8
    #define START_SEC_VAR_CLEARED_8
#elif defined UDS_STOP_SEC_VAR_CLEARED_8
    #undef UDS_STOP_SEC_VAR_CLEARED_8
    #define STOP_SEC_VAR_CLEARED_8
#elif defined UDS_START_SEC_VAR_CLEARED_16
    #undef UDS_START_SEC_VAR_CLEARED_16
    #define START_SEC_VAR_CLEARED_16
#elif defined UDS_STOP_SEC_VAR_CLEARED_16
    #undef UDS_STOP_SEC_VAR_CLEARED_16
    #define STOP_SEC_VAR_CLEARED_16
#elif defined UDS_START_SEC_VAR_CLEARED_32
    #undef UDS_START_SEC_VAR_CLEARED_32
    #define START_SEC_VAR_CLEARED_32
#elif defined UDS_STOP_SEC_VAR_CLEARED_32
    #undef UDS_STOP_SEC_VAR_CLEARED_32
    #define STOP_SEC_VAR_CLEARED_32
#elif defined UDS_START_SEC_VAR_CLEARED_PTR
    #undef UDS_START_SEC_VAR_CLEARED_PTR
    #define START_SEC_VAR_CLEARED_PTR
#elif defined UDS_STOP_SEC_VAR_CLEARED_PTR
    #undef UDS_STOP_SEC_VAR_CLEARED_PTR
    #define STOP_SEC_VAR_CLEARED_PTR
#elif defined UDS_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_VAR_CLEARED_UNSPECIFIED
    #define START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #define STOP_SEC_VAR_CLEARED_UNSPECIFIED

/* VAR_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_VAR_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_8
    #define START_SEC_VAR_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_8
    #define STOP_SEC_VAR_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_16
    #define START_SEC_VAR_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_16
    #define STOP_SEC_VAR_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_32
    #define START_SEC_VAR_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_32
    #define STOP_SEC_VAR_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_PTR
    #define START_SEC_VAR_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_PTR
    #define STOP_SEC_VAR_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_VAR_POWER_ON_CLEAR_UNSPECIFIED

/* VAR_INIT */
#elif defined UDS_START_SEC_VAR_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_INIT_BOOLEAN
    #define START_SEC_VAR_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_INIT_BOOLEAN
    #define STOP_SEC_VAR_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_INIT_8
    #undef UDS_START_SEC_VAR_INIT_8
    #define START_SEC_VAR_INIT_8
#elif defined UDS_STOP_SEC_VAR_INIT_8
    #undef UDS_STOP_SEC_VAR_INIT_8
    #define STOP_SEC_VAR_INIT_8
#elif defined UDS_START_SEC_VAR_INIT_16
    #undef UDS_START_SEC_VAR_INIT_16
    #define START_SEC_VAR_INIT_16
#elif defined UDS_STOP_SEC_VAR_INIT_16
    #undef UDS_STOP_SEC_VAR_INIT_16
    #define STOP_SEC_VAR_INIT_16
#elif defined UDS_START_SEC_VAR_INIT_32
    #undef UDS_START_SEC_VAR_INIT_32
    #define START_SEC_VAR_INIT_32
#elif defined UDS_STOP_SEC_VAR_INIT_32
    #undef UDS_STOP_SEC_VAR_INIT_32
    #define STOP_SEC_VAR_INIT_32
#elif defined UDS_START_SEC_VAR_INIT_PTR
    #undef UDS_START_SEC_VAR_INIT_PTR
    #define START_SEC_VAR_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_INIT_PTR
    #undef UDS_STOP_SEC_VAR_INIT_PTR
    #define STOP_SEC_VAR_INIT_PTR
#elif defined UDS_START_SEC_VAR_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_INIT_UNSPECIFIED
    #define START_SEC_VAR_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_INIT_UNSPECIFIED

/* VAR_POWER_ON_INIT */
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #define START_SEC_VAR_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_8
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_8
    #define START_SEC_VAR_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_8
    #define STOP_SEC_VAR_POWER_ON_INIT_8
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_16
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_16
    #define START_SEC_VAR_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_16
    #define STOP_SEC_VAR_POWER_ON_INIT_16
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_32
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_32
    #define START_SEC_VAR_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_32
    #define STOP_SEC_VAR_POWER_ON_INIT_32
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_PTR
    #define START_SEC_VAR_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_PTR
    #define STOP_SEC_VAR_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED

/* INTERNAL_VAR_NO_INIT */
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #define START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_8
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_8
    #define START_SEC_INTERNAL_VAR_NO_INIT_8
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_8
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_8
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_8
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_16
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_16
    #define START_SEC_INTERNAL_VAR_NO_INIT_16
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_16
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_16
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_16
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_32
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_32
    #define START_SEC_INTERNAL_VAR_NO_INIT_32
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_32
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_32
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_32
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_PTR
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_PTR
    #define START_SEC_INTERNAL_VAR_NO_INIT_PTR
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_PTR
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_PTR
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_PTR
#elif defined UDS_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #define START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #define STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED

/* INTERNAL_VAR_CLEARED */
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #define START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #define STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_8
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_8
    #define START_SEC_INTERNAL_VAR_CLEARED_8
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #define STOP_SEC_INTERNAL_VAR_CLEARED_8
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_16
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_16
    #define START_SEC_INTERNAL_VAR_CLEARED_16
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #define STOP_SEC_INTERNAL_VAR_CLEARED_16
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_32
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_32
    #define START_SEC_INTERNAL_VAR_CLEARED_32
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #define STOP_SEC_INTERNAL_VAR_CLEARED_32
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_PTR
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_PTR
    #define START_SEC_INTERNAL_VAR_CLEARED_PTR
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_PTR
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_PTR
    #define STOP_SEC_INTERNAL_VAR_CLEARED_PTR
#elif defined UDS_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #define START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #define STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED

/* INTERNAL_VAR_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_CLEAR_UNSPECIFIED

/* INTERNAL_VAR_INIT */
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #define START_SEC_INTERNAL_VAR_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #define STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_8
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_8
    #define START_SEC_INTERNAL_VAR_INIT_8
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_8
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_8
    #define STOP_SEC_INTERNAL_VAR_INIT_8
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_16
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_16
    #define START_SEC_INTERNAL_VAR_INIT_16
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_16
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_16
    #define STOP_SEC_INTERNAL_VAR_INIT_16
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_32
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_32
    #define START_SEC_INTERNAL_VAR_INIT_32
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_32
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_32
    #define STOP_SEC_INTERNAL_VAR_INIT_32
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_PTR
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_PTR
    #define START_SEC_INTERNAL_VAR_INIT_PTR
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_PTR
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_PTR
    #define STOP_SEC_INTERNAL_VAR_INIT_PTR
#elif defined UDS_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef UDS_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #define START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #define STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
/* INTERNAL_VAR_POWER_ON_INIT */
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
/* VAR_SAVED_ZONE_NO_INIT */
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_8
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_8
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_8
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_8
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_8
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_8
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_16
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_16
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_16
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_16
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_16
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_16
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_32
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_32
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_32
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_32
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_32
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_32
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_PTR
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
    #define START_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
/* VAR_SAVED_ZONE_CLEARED */
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_8
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_8
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_8
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_8
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_8
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_8
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_16
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_16
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_16
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_16
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_16
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_16
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_32
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_32
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_32
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_32
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_32
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_32
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_PTR
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_PTR
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_PTR
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_PTR
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_PTR
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_PTR
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
    #define START_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
    #define STOP_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
/* VAR_SAVED_ZONE_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEAR_UNSPECIFIED
/* VAR_SAVED_ZONE_INIT */
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
    #define START_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_8
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_8
    #define START_SEC_VAR_SAVED_ZONE_INIT_8
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_8
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_8
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_8
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_16
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_16
    #define START_SEC_VAR_SAVED_ZONE_INIT_16
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_16
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_16
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_16
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_32
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_32
    #define START_SEC_VAR_SAVED_ZONE_INIT_32
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_32
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_32
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_32
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_PTR
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_PTR
    #define START_SEC_VAR_SAVED_ZONE_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_PTR
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_PTR
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_PTR
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
    #define START_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
/* VAR_SAVED_ZONE_POWER_ON_INIT */
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
/* CONST_NO_INIT */
#elif defined UDS_START_SEC_CONST_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_NO_INIT_BOOLEAN
    #define START_SEC_CONST_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_NO_INIT_BOOLEAN
    #define STOP_SEC_CONST_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_NO_INIT_8
    #undef UDS_START_SEC_CONST_NO_INIT_8
    #define START_SEC_CONST_NO_INIT_8
#elif defined UDS_STOP_SEC_CONST_NO_INIT_8
    #undef UDS_STOP_SEC_CONST_NO_INIT_8
    #define STOP_SEC_CONST_NO_INIT_8
#elif defined UDS_START_SEC_CONST_NO_INIT_16
    #undef UDS_START_SEC_CONST_NO_INIT_16
    #define START_SEC_CONST_NO_INIT_16
#elif defined UDS_STOP_SEC_CONST_NO_INIT_16
    #undef UDS_STOP_SEC_CONST_NO_INIT_16
    #define STOP_SEC_CONST_NO_INIT_16
#elif defined UDS_START_SEC_CONST_NO_INIT_32
    #undef UDS_START_SEC_CONST_NO_INIT_32
    #define START_SEC_CONST_NO_INIT_32
#elif defined UDS_STOP_SEC_CONST_NO_INIT_32
    #undef UDS_STOP_SEC_CONST_NO_INIT_32
    #define STOP_SEC_CONST_NO_INIT_32
#elif defined UDS_START_SEC_CONST_NO_INIT_PTR
    #undef UDS_START_SEC_CONST_NO_INIT_PTR
    #define START_SEC_CONST_NO_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_NO_INIT_PTR
    #undef UDS_STOP_SEC_CONST_NO_INIT_PTR
    #define STOP_SEC_CONST_NO_INIT_PTR
#elif defined UDS_START_SEC_CONST_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_NO_INIT_UNSPECIFIED
    #define START_SEC_CONST_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_NO_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_NO_INIT_UNSPECIFIED
/* CONST_CLEARED */
#elif defined UDS_START_SEC_CONST_CLEARED_BOOLEAN
    #undef UDS_START_SEC_CONST_CLEARED_BOOLEAN
    #define START_SEC_CONST_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_CONST_CLEARED_BOOLEAN
    #define STOP_SEC_CONST_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_CONST_CLEARED_8
    #undef UDS_START_SEC_CONST_CLEARED_8
    #define START_SEC_CONST_CLEARED_8
#elif defined UDS_STOP_SEC_CONST_CLEARED_8
    #undef UDS_STOP_SEC_CONST_CLEARED_8
    #define STOP_SEC_CONST_CLEARED_8
#elif defined UDS_START_SEC_CONST_CLEARED_16
    #undef UDS_START_SEC_CONST_CLEARED_16
    #define START_SEC_CONST_CLEARED_16
#elif defined UDS_STOP_SEC_CONST_CLEARED_16
    #undef UDS_STOP_SEC_CONST_CLEARED_16
    #define STOP_SEC_CONST_CLEARED_16
#elif defined UDS_START_SEC_CONST_CLEARED_32
    #undef UDS_START_SEC_CONST_CLEARED_32
    #define START_SEC_CONST_CLEARED_32
#elif defined UDS_STOP_SEC_CONST_CLEARED_32
    #undef UDS_STOP_SEC_CONST_CLEARED_32
    #define STOP_SEC_CONST_CLEARED_32
#elif defined UDS_START_SEC_CONST_CLEARED_PTR
    #undef UDS_START_SEC_CONST_CLEARED_PTR
    #define START_SEC_CONST_CLEARED_PTR
#elif defined UDS_STOP_SEC_CONST_CLEARED_PTR
    #undef UDS_STOP_SEC_CONST_CLEARED_PTR
    #define STOP_SEC_CONST_CLEARED_PTR
#elif defined UDS_START_SEC_CONST_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_CONST_CLEARED_UNSPECIFIED
    #define START_SEC_CONST_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_CLEARED_UNSPECIFIED
    #define STOP_SEC_CONST_CLEARED_UNSPECIFIED
/* CONST_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_CONST_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_8
    #define START_SEC_CONST_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_8
    #define STOP_SEC_CONST_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_16
    #define START_SEC_CONST_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_16
    #define STOP_SEC_CONST_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_32
    #define START_SEC_CONST_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_32
    #define STOP_SEC_CONST_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_PTR
    #define START_SEC_CONST_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_PTR
    #define STOP_SEC_CONST_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_CONST_POWER_ON_CLEAR_UNSPECIFIED
/* CONST_INIT */
#elif defined UDS_START_SEC_CONST_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_INIT_BOOLEAN
    #define START_SEC_CONST_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_INIT_BOOLEAN
    #define STOP_SEC_CONST_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_INIT_8
    #undef UDS_START_SEC_CONST_INIT_8
    #define START_SEC_CONST_INIT_8
#elif defined UDS_STOP_SEC_CONST_INIT_8
    #undef UDS_STOP_SEC_CONST_INIT_8
    #define STOP_SEC_CONST_INIT_8
#elif defined UDS_START_SEC_CONST_INIT_16
    #undef UDS_START_SEC_CONST_INIT_16
    #define START_SEC_CONST_INIT_16
#elif defined UDS_STOP_SEC_CONST_INIT_16
    #undef UDS_STOP_SEC_CONST_INIT_16
    #define STOP_SEC_CONST_INIT_16
#elif defined UDS_START_SEC_CONST_INIT_32
    #undef UDS_START_SEC_CONST_INIT_32
    #define START_SEC_CONST_INIT_32
#elif defined UDS_STOP_SEC_CONST_INIT_32
    #undef UDS_STOP_SEC_CONST_INIT_32
    #define STOP_SEC_CONST_INIT_32
#elif defined UDS_START_SEC_CONST_INIT_PTR
    #undef UDS_START_SEC_CONST_INIT_PTR
    #define START_SEC_CONST_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_INIT_PTR
    #undef UDS_STOP_SEC_CONST_INIT_PTR
    #define STOP_SEC_CONST_INIT_PTR
#elif defined UDS_START_SEC_CONST_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_INIT_UNSPECIFIED
    #define START_SEC_CONST_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_INIT_UNSPECIFIED
/* CONST_POWER_ON_INIT */
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_BOOLEAN
    #define START_SEC_CONST_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_CONST_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_8
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_8
    #define START_SEC_CONST_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_8
    #define STOP_SEC_CONST_POWER_ON_INIT_8
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_16
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_16
    #define START_SEC_CONST_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_16
    #define STOP_SEC_CONST_POWER_ON_INIT_16
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_32
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_32
    #define START_SEC_CONST_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_32
    #define STOP_SEC_CONST_POWER_ON_INIT_32
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_PTR
    #define START_SEC_CONST_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_PTR
    #define STOP_SEC_CONST_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_POWER_ON_INIT_UNSPECIFIED
/* CALIB_NO_INIT */
#elif defined UDS_START_SEC_CALIB_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_CALIB_NO_INIT_BOOLEAN
    #define START_SEC_CALIB_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CALIB_NO_INIT_BOOLEAN
    #define STOP_SEC_CALIB_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_CALIB_NO_INIT_8
    #undef UDS_START_SEC_CALIB_NO_INIT_8
    #define START_SEC_CALIB_NO_INIT_8
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_8
    #undef UDS_STOP_SEC_CALIB_NO_INIT_8
    #define STOP_SEC_CALIB_NO_INIT_8
#elif defined UDS_START_SEC_CALIB_NO_INIT_16
    #undef UDS_START_SEC_CALIB_NO_INIT_16
    #define START_SEC_CALIB_NO_INIT_16
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_16
    #undef UDS_STOP_SEC_CALIB_NO_INIT_16
    #define STOP_SEC_CALIB_NO_INIT_16
#elif defined UDS_START_SEC_CALIB_NO_INIT_32
    #undef UDS_START_SEC_CALIB_NO_INIT_32
    #define START_SEC_CALIB_NO_INIT_32
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_32
    #undef UDS_STOP_SEC_CALIB_NO_INIT_32
    #define STOP_SEC_CALIB_NO_INIT_32
#elif defined UDS_START_SEC_CALIB_NO_INIT_PTR
    #undef UDS_START_SEC_CALIB_NO_INIT_PTR
    #define START_SEC_CALIB_NO_INIT_PTR
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_PTR
    #undef UDS_STOP_SEC_CALIB_NO_INIT_PTR
    #define STOP_SEC_CALIB_NO_INIT_PTR
#elif defined UDS_START_SEC_CALIB_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CALIB_NO_INIT_UNSPECIFIED
    #define START_SEC_CALIB_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CALIB_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CALIB_NO_INIT_UNSPECIFIED
    #define STOP_SEC_CALIB_NO_INIT_UNSPECIFIED
/* CALIB_CLEARED */
#elif defined UDS_START_SEC_CALIB_CLEARED_BOOLEAN
    #undef UDS_START_SEC_CALIB_CLEARED_BOOLEAN
    #define START_SEC_CALIB_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_CALIB_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_CALIB_CLEARED_BOOLEAN
    #define STOP_SEC_CALIB_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_CALIB_CLEARED_8
    #undef UDS_START_SEC_CALIB_CLEARED_8
    #define START_SEC_CALIB_CLEARED_8
#elif defined UDS_STOP_SEC_CALIB_CLEARED_8
    #undef UDS_STOP_SEC_CALIB_CLEARED_8
    #define STOP_SEC_CALIB_CLEARED_8
#elif defined UDS_START_SEC_CALIB_CLEARED_16
    #undef UDS_START_SEC_CALIB_CLEARED_16
    #define START_SEC_CALIB_CLEARED_16
#elif defined UDS_STOP_SEC_CALIB_CLEARED_16
    #undef UDS_STOP_SEC_CALIB_CLEARED_16
    #define STOP_SEC_CALIB_CLEARED_16
#elif defined UDS_START_SEC_CALIB_CLEARED_32
    #undef UDS_START_SEC_CALIB_CLEARED_32
    #define START_SEC_CALIB_CLEARED_32
#elif defined UDS_STOP_SEC_CALIB_CLEARED_32
    #undef UDS_STOP_SEC_CALIB_CLEARED_32
    #define STOP_SEC_CALIB_CLEARED_32
#elif defined UDS_START_SEC_CALIB_CLEARED_PTR
    #undef UDS_START_SEC_CALIB_CLEARED_PTR
    #define START_SEC_CALIB_CLEARED_PTR
#elif defined UDS_STOP_SEC_CALIB_CLEARED_PTR
    #undef UDS_STOP_SEC_CALIB_CLEARED_PTR
    #define STOP_SEC_CALIB_CLEARED_PTR
#elif defined UDS_START_SEC_CALIB_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_CALIB_CLEARED_UNSPECIFIED
    #define START_SEC_CALIB_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_CALIB_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_CALIB_CLEARED_UNSPECIFIED
    #define STOP_SEC_CALIB_CLEARED_UNSPECIFIED
/* CALIB_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_8
    #define START_SEC_CALIB_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_8
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_16
    #define START_SEC_CALIB_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_16
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_32
    #define START_SEC_CALIB_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_32
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_PTR
    #define START_SEC_CALIB_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_PTR
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_CALIB_POWER_ON_CLEAR_UNSPECIFIED
/* CALIB_INIT */
#elif defined UDS_START_SEC_CALIB_INIT_BOOLEAN
    #undef UDS_START_SEC_CALIB_INIT_BOOLEAN
    #define START_SEC_CALIB_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CALIB_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CALIB_INIT_BOOLEAN
    #define STOP_SEC_CALIB_INIT_BOOLEAN
#elif defined UDS_START_SEC_CALIB_INIT_8
    #undef UDS_START_SEC_CALIB_INIT_8
    #define START_SEC_CALIB_INIT_8
#elif defined UDS_STOP_SEC_CALIB_INIT_8
    #undef UDS_STOP_SEC_CALIB_INIT_8
    #define STOP_SEC_CALIB_INIT_8
#elif defined UDS_START_SEC_CALIB_INIT_16
    #undef UDS_START_SEC_CALIB_INIT_16
    #define START_SEC_CALIB_INIT_16
#elif defined UDS_STOP_SEC_CALIB_INIT_16
    #undef UDS_STOP_SEC_CALIB_INIT_16
    #define STOP_SEC_CALIB_INIT_16
#elif defined UDS_START_SEC_CALIB_INIT_32
    #undef UDS_START_SEC_CALIB_INIT_32
    #define START_SEC_CALIB_INIT_32
#elif defined UDS_STOP_SEC_CALIB_INIT_32
    #undef UDS_STOP_SEC_CALIB_INIT_32
    #define STOP_SEC_CALIB_INIT_32
#elif defined UDS_START_SEC_CALIB_INIT_PTR
    #undef UDS_START_SEC_CALIB_INIT_PTR
    #define START_SEC_CALIB_INIT_PTR
#elif defined UDS_STOP_SEC_CALIB_INIT_PTR
    #undef UDS_STOP_SEC_CALIB_INIT_PTR
    #define STOP_SEC_CALIB_INIT_PTR
#elif defined UDS_START_SEC_CALIB_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CALIB_INIT_UNSPECIFIED
    #define START_SEC_CALIB_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CALIB_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CALIB_INIT_UNSPECIFIED
    #define STOP_SEC_CALIB_INIT_UNSPECIFIED
/* CALIB_POWER_ON_INIT */
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_BOOLEAN
    #define START_SEC_CALIB_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_CALIB_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_8
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_8
    #define START_SEC_CALIB_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_8
    #define STOP_SEC_CALIB_POWER_ON_INIT_8
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_16
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_16
    #define START_SEC_CALIB_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_16
    #define STOP_SEC_CALIB_POWER_ON_INIT_16
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_32
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_32
    #define START_SEC_CALIB_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_32
    #define STOP_SEC_CALIB_POWER_ON_INIT_32
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_PTR
    #define START_SEC_CALIB_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_PTR
    #define STOP_SEC_CALIB_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_CALIB_POWER_ON_INIT_UNSPECIFIED
/* CONFIG_DATA_NO_INIT */
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
    #define START_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
    #define STOP_SEC_CONFIG_DATA_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_8
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_8
    #define START_SEC_CONFIG_DATA_NO_INIT_8
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_8
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_8
    #define STOP_SEC_CONFIG_DATA_NO_INIT_8
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_16
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_16
    #define START_SEC_CONFIG_DATA_NO_INIT_16
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_16
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_16
    #define STOP_SEC_CONFIG_DATA_NO_INIT_16
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_32
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_32
    #define START_SEC_CONFIG_DATA_NO_INIT_32
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_32
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_32
    #define STOP_SEC_CONFIG_DATA_NO_INIT_32
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_PTR
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_PTR
    #define START_SEC_CONFIG_DATA_NO_INIT_PTR
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_PTR
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_PTR
    #define STOP_SEC_CONFIG_DATA_NO_INIT_PTR
#elif defined UDS_START_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
    #define START_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
    #define STOP_SEC_CONFIG_DATA_NO_INIT_UNSPECIFIED
/* CONFIG_DATA_CLEARED */
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_BOOLEAN
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_BOOLEAN
    #define START_SEC_CONFIG_DATA_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_BOOLEAN
    #define STOP_SEC_CONFIG_DATA_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_8
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_8
    #define START_SEC_CONFIG_DATA_CLEARED_8
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_8
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_8
    #define STOP_SEC_CONFIG_DATA_CLEARED_8
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_16
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_16
    #define START_SEC_CONFIG_DATA_CLEARED_16
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_16
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_16
    #define STOP_SEC_CONFIG_DATA_CLEARED_16
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_32
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_32
    #define START_SEC_CONFIG_DATA_CLEARED_32
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_32
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_32
    #define STOP_SEC_CONFIG_DATA_CLEARED_32
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_PTR
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_PTR
    #define START_SEC_CONFIG_DATA_CLEARED_PTR
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_PTR
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_PTR
    #define STOP_SEC_CONFIG_DATA_CLEARED_PTR
#elif defined UDS_START_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
    #define START_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
    #define STOP_SEC_CONFIG_DATA_CLEARED_UNSPECIFIED
/* CONFIG_DATA_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_CONFIG_DATA_POWER_ON_CLEAR_UNSPECIFIED
/* CONFIG_DATA_INIT */
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_BOOLEAN
    #undef UDS_START_SEC_CONFIG_DATA_INIT_BOOLEAN
    #define START_SEC_CONFIG_DATA_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_BOOLEAN
    #define STOP_SEC_CONFIG_DATA_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_8
    #undef UDS_START_SEC_CONFIG_DATA_INIT_8
    #define START_SEC_CONFIG_DATA_INIT_8
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_8
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_8
    #define STOP_SEC_CONFIG_DATA_INIT_8
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_16
    #undef UDS_START_SEC_CONFIG_DATA_INIT_16
    #define START_SEC_CONFIG_DATA_INIT_16
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_16
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_16
    #define STOP_SEC_CONFIG_DATA_INIT_16
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_32
    #undef UDS_START_SEC_CONFIG_DATA_INIT_32
    #define START_SEC_CONFIG_DATA_INIT_32
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_32
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_32
    #define STOP_SEC_CONFIG_DATA_INIT_32
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_PTR
    #undef UDS_START_SEC_CONFIG_DATA_INIT_PTR
    #define START_SEC_CONFIG_DATA_INIT_PTR
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_PTR
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_PTR
    #define STOP_SEC_CONFIG_DATA_INIT_PTR
#elif defined UDS_START_SEC_CONFIG_DATA_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONFIG_DATA_INIT_UNSPECIFIED
    #define START_SEC_CONFIG_DATA_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONFIG_DATA_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONFIG_DATA_INIT_UNSPECIFIED
    #define STOP_SEC_CONFIG_DATA_INIT_UNSPECIFIED
/* CONFIG_DATA_POWER_ON_INIT */
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_8
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_8
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_8
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_8
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_16
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_16
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_16
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_16
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_32
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_32
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_32
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_32
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_CONFIG_DATA_POWER_ON_INIT_UNSPECIFIED
/* CONST_PBCFG_NO_INIT */
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
    #define START_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
    #define STOP_SEC_CONST_PBCFG_NO_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_8
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_8
    #define START_SEC_CONST_PBCFG_NO_INIT_8
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_8
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_8
    #define STOP_SEC_CONST_PBCFG_NO_INIT_8
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_16
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_16
    #define START_SEC_CONST_PBCFG_NO_INIT_16
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_16
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_16
    #define STOP_SEC_CONST_PBCFG_NO_INIT_16
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_32
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_32
    #define START_SEC_CONST_PBCFG_NO_INIT_32
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_32
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_32
    #define STOP_SEC_CONST_PBCFG_NO_INIT_32
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_PTR
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_PTR
    #define START_SEC_CONST_PBCFG_NO_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_PTR
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_PTR
    #define STOP_SEC_CONST_PBCFG_NO_INIT_PTR
#elif defined UDS_START_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
    #define START_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_PBCFG_NO_INIT_UNSPECIFIED
/* CONST_PBCFG_CLEARED */
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_BOOLEAN
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_BOOLEAN
    #define START_SEC_CONST_PBCFG_CLEARED_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_BOOLEAN
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_BOOLEAN
    #define STOP_SEC_CONST_PBCFG_CLEARED_BOOLEAN
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_8
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_8
    #define START_SEC_CONST_PBCFG_CLEARED_8
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_8
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_8
    #define STOP_SEC_CONST_PBCFG_CLEARED_8
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_16
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_16
    #define START_SEC_CONST_PBCFG_CLEARED_16
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_16
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_16
    #define STOP_SEC_CONST_PBCFG_CLEARED_16
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_32
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_32
    #define START_SEC_CONST_PBCFG_CLEARED_32
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_32
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_32
    #define STOP_SEC_CONST_PBCFG_CLEARED_32
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_PTR
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_PTR
    #define START_SEC_CONST_PBCFG_CLEARED_PTR
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_PTR
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_PTR
    #define STOP_SEC_CONST_PBCFG_CLEARED_PTR
#elif defined UDS_START_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
    #undef UDS_START_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
    #define START_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
    #define STOP_SEC_CONST_PBCFG_CLEARED_UNSPECIFIED
/* CONST_PBCFG_POWER_ON_CLEAR */
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_BOOLEAN
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_8
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_16
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_32
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_PTR
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
    #define START_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
    #define STOP_SEC_CONST_PBCFG_POWER_ON_CLEAR_UNSPECIFIED
/* CONST_PBCFG_INIT */
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_PBCFG_INIT_BOOLEAN
    #define START_SEC_CONST_PBCFG_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_BOOLEAN
    #define STOP_SEC_CONST_PBCFG_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_8
    #undef UDS_START_SEC_CONST_PBCFG_INIT_8
    #define START_SEC_CONST_PBCFG_INIT_8
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_8
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_8
    #define STOP_SEC_CONST_PBCFG_INIT_8
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_16
    #undef UDS_START_SEC_CONST_PBCFG_INIT_16
    #define START_SEC_CONST_PBCFG_INIT_16
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_16
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_16
    #define STOP_SEC_CONST_PBCFG_INIT_16
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_32
    #undef UDS_START_SEC_CONST_PBCFG_INIT_32
    #define START_SEC_CONST_PBCFG_INIT_32
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_32
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_32
    #define STOP_SEC_CONST_PBCFG_INIT_32
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_PTR
    #undef UDS_START_SEC_CONST_PBCFG_INIT_PTR
    #define START_SEC_CONST_PBCFG_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_PTR
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_PTR
    #define STOP_SEC_CONST_PBCFG_INIT_PTR
#elif defined UDS_START_SEC_CONST_PBCFG_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_PBCFG_INIT_UNSPECIFIED
    #define START_SEC_CONST_PBCFG_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_PBCFG_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_PBCFG_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_PBCFG_INIT_UNSPECIFIED
/* CONST_PBCFG_POWER_ON_INIT */
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_BOOLEAN
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_8
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_8
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_8
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_8
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_8
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_8
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_16
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_16
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_16
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_16
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_16
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_16
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_32
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_32
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_32
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_32
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_32
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_32
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_PTR
#elif defined UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_START_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
#elif defined UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
    #undef UDS_STOP_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_CONST_PBCFG_POWER_ON_INIT_UNSPECIFIED
#else
    #error  "UDS not include this section"
#endif
#include "MemMap.h"

#endif

