/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2020)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : ComStack_Cfg.h                                              **
**                                                                            **
**  Created on  : 2022/10/23 10:40:44                                         **
**  Author      : zhengfei.li                                                 **
**  Vendor      :                                                             **
**  DESCRIPTION : Communication Stack Types (generated by EcuC)               **
**                                                                            **
**  SPECIFICATION(S) :  AUTOSAR classic Platform 4.2.2 and R19_11             **
**                                                                            **
*******************************************************************************/
/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/
#ifndef COMSTACK_CFG_H
#define COMSTACK_CFG_H
/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/


/*******************************************************************************
**                      Typedefs                                              **
*******************************************************************************/
typedef uint16       PduIdType;

typedef uint16       PduLengthType;


#endif /* COMSTACK_CFG_H */
